name: Running Runners

on:
  push:
    branches: [main]

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: show it
        run: ls -al

  second_job:
    name: Second Job
    runs-on: [ubuntu-latest, macos-latest]

    steps:
      - name: checkout first
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main
      - name: list directorties
        run: ls -al
      - name: run tests
        run: npx jest

