name: Multi Event workflow
runner-name: Multi Event Runner

on:
  push: [main, dev]
  pull_request: [main]

jobs:
  multi_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: multi event job name
        run: |
          echo "Actor $GITHUB_ACTOR"
          echo "Action: $GITHUB_ACTION"
