name: name for sachdule
runner-name: runner name for schedule

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  hello_world:
    name: my job for schedule
    runs-on: ubuntu-latest
    steps:
      - name: echoing time
        run: echo "the time is $(date)"
